### ISSUE TITLE
Add star button on the generated website

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-demos-2022#26]
On youtube we now recommend people to go on the website but we're missing opportunities to get stars on this repo and increase recommendations through GitHub. Adding a star button would be nice to invite people to star the repo from the website.

**Comment by Xananax** [comment]
Reminder to self:

```html
<a class="github-button" href="https://github.com/gdquest/godot-demos-2022" data-color-scheme="no-preference: light; light: light; dark: dark;" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star gdquest/godot-demos-2022 on GitHub">Star</a>

this in head or before end of body:
<script async defer src="https://buttons.github.io/buttons.js"></script>
```

Do we want also other buttons? https://buttons.github.io/

We already have the github "fork me" triangular corner.

I think I'll add a "fork" and "follow" buttons also just to have a nicer design

**Comment by NathanLovato** [comment]
Sure, go ahead!
